package cn.itcast.ssm.po;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.className
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    private Integer classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.classId
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    private Integer classid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.groud
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    private Float groud;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.examId
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    private Integer examid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.examIdNum
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    private Integer examidnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.examDate
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    private String examdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.className
     *
     * @return the value of student.className
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public Integer getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.className
     *
     * @param classname the value for student.className
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public void setClassname(Integer classname) {
        this.classname = classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.classId
     *
     * @return the value of student.classId
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.classId
     *
     * @param classid the value for student.classId
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.groud
     *
     * @return the value of student.groud
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public Float getGroud() {
        return groud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.groud
     *
     * @param groud the value for student.groud
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public void setGroud(Float groud) {
        this.groud = groud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.examId
     *
     * @return the value of student.examId
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public Integer getExamid() {
        return examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.examId
     *
     * @param examid the value for student.examId
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public void setExamid(Integer examid) {
        this.examid = examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.examIdNum
     *
     * @return the value of student.examIdNum
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public Integer getExamidnum() {
        return examidnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.examIdNum
     *
     * @param examidnum the value for student.examIdNum
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public void setExamidnum(Integer examidnum) {
        this.examidnum = examidnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.examDate
     *
     * @return the value of student.examDate
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public String getExamdate() {
        return examdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.examDate
     *
     * @param examdate the value for student.examDate
     *
     * @mbg.generated Sun Nov 05 14:33:54 CST 2017
     */
    public void setExamdate(String examdate) {
        this.examdate = examdate == null ? null : examdate.trim();
    }
}